tag: user.mouse_control_chicken_showing
and tag: user.mouse_control_chicken_quick_action
-
^<user.mouse_control_chicken_main_coordinates>$: user.mouse_control_chicken_perform_quick_action(mouse_control_chicken_main_coordinates)